version: "3"
services:
  linktreeDB:
    image: postgres:12.0-alpine
    container_name: linktreeDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
