import type { Metadata } from "next";
import { Bricolage_Grotesque as Font } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";
import React from "react";
import { AppProviders } from "@/providers";

const font = Font({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <AppProviders>
        <html lang="en">
          <body
            className={cn(
              "min-h-screen bg-background font-sans antialiased",
              font.variable,
            )}
          >
            {children}
          </body>
        </html>
      </AppProviders>
    </ClerkProvider>
  );
}
